### ISSUE TITLE
No module named gala

### ISSUE THREAD

**Issue by jaimebayes** [janelia-flyem/gala#38]
Hi, 
I installed gala into two machines (win8 & ubuntu). Apparently it was correctly installed.
But when I try to run the examples into test folder, it sends this message:

>>>python test_agglo.py
ImportError: No module named gala

I included gala folder into PATH (win8) and .profile file (ubuntu), but this happens on both systems.
so what I did wrong? what I have to do to run it?

thanks, jaime

**Comment by jni** [comment]
@jaimebayes did you ever manage to get gala working?

**Comment by jaimebayes** [comment]
Yeah, Juan, I just got permissions to folder using chown -T jaimebayes ./*

thanks, Juan

On Tue, Feb 17, 2015 at 3:52 AM, Juan Nunez-Iglesias <
notifications@github.com> wrote:

> @jaimebayes <https://github.com/jaimebayes> did you ever manage to get
> gala working?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/janelia-flyem/gala/issues/38#issuecomment-74635228>.
>



-- 

*Jaime Lopez Carvajal*

**Comment by jni** [comment]
Awesome, thanks for letting me know. Sorry that I couldn't be more helpful with the Windows install!
