### ISSUE TITLE
help me new to python

### ISSUE THREAD

**Issue by BOOM5s** [janelia-flyem/gala#95]
`import gala.coordinates as gc
import gala.dynamics as gd
import gala.potential as gp`

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-48-9cec35fb071d> in <module>
     13 
     14 #gala imports
---> 15 import gala.coordinates as gc
     16 import gala.dynamics as gd
     17 import gala.potential as gp

~/opt/anaconda3/lib/python3.7/site-packages/gala/__init__.py in <module>
     24 if not _ASTROPY_SETUP_:
     25     from . import coordinates
---> 26     from . import dynamics
     27     from . import integrate
     28     from . import potential

~/opt/anaconda3/lib/python3.7/site-packages/gala/dynamics/__init__.py in <module>
      1 from .core import PhaseSpacePosition, CartesianPhaseSpacePosition
      2 from .orbit import Orbit, CartesianOrbit
----> 3 from .analyticactionangle import *
      4 from .actionangle import *
      5 from .nonlinear import *

~/opt/anaconda3/lib/python3.7/site-packages/gala/dynamics/analyticactionangle.py in <module>
     11 
     12 # Project
---> 13 from ..potential import (Hamiltonian, PotentialBase,
     14                          IsochronePotential, HarmonicOscillatorPotential)
     15 from ..util import atleast_2d

~/opt/anaconda3/lib/python3.7/site-packages/gala/potential/__init__.py in <module>
----> 1 from .potential import *
      2 from .hamiltonian import *
      3 from .frame import *
      4 from .scf import SCFPotential

~/opt/anaconda3/lib/python3.7/site-packages/gala/potential/potential/__init__.py in <module>
      2 from .cpotential import *
      3 from .ccompositepotential import *
----> 4 from .builtin import *
      5 from .io import *
      6 from .util import *

~/opt/anaconda3/lib/python3.7/site-packages/gala/potential/potential/builtin/__init__.py in <module>
      1 from .cybuiltin import *
      2 from .pybuiltin import *
----> 3 from .special import *

~/opt/anaconda3/lib/python3.7/site-packages/gala/potential/potential/builtin/special.py in <module>
      6 # from .cpotential import CCompositePotential
      7 # from ..core import CompositePotential
----> 8 from .cybuiltin import (HernquistPotential,
      9                         MiyamotoNagaiPotential,
     10                         LogarithmicPotential,

ImportError: cannot import name 'HernquistPotential' from 'gala.potential.potential.builtin.cybuiltin' (unknown location)``

**Comment by jni** [comment]
@BOOM5s wrong gala, it seems! None of those modules are part of this package.
